import type { ExaminerProfile } from '@/components/examiners/examinerTypes';

export const VERIFIED_EXPERT_PROFILES: ExaminerProfile[] = [
  {
    _id: 'expert-baek-kyung-woo',
    name: '백경우',
    position: '변리사',
    companyName: '백경특허법률사무소',
    category: 'intellectual_property',
    specialties: ['특허', '상표', '디자인'],
    imageUrl: '/images/examiners/baek-kyung-woo.png',
    imageAlt: '백경우 전문가 사진',
    sortOrder: 1,
    legacyKey: 'baek-kyung-woo',
    isPublished: true,
  },
  {
    _id: 'expert-sung-min-seok',
    name: '성민석',
    position: '세무사',
    companyName: '세무법인 우진',
    category: 'tax',
    specialties: ['세무조사', '절세전략', '기업자문'],
    imageUrl: '/images/examiners/sung-min-seok.png',
    imageAlt: '성민석 전문가 사진',
    sortOrder: 2,
    legacyKey: 'sung-min-seok',
    isPublished: true,
  },
  {
    _id: 'expert-jeon-ki-hong',
    name: '전기홍',
    position: '행정사',
    companyName: '창성',
    category: 'administration',
    specialties: ['인허가', '행정심판', '행정소송'],
    imageUrl: '/images/examiners/jeon-ki-hong.png',
    imageAlt: '전기홍 전문가 사진',
    sortOrder: 3,
    legacyKey: 'jeon-ki-hong',
    isPublished: true,
  },
  {
    _id: 'expert-choi-il-hyun',
    name: '최일현',
    position: '회계사',
    companyName: '우일회계법인',
    category: 'accounting',
    specialties: ['재무제표', '회계감사', '세무조정'],
    imageUrl: '/images/examiners/choi-il-hyun.png',
    imageAlt: '최일현 전문가 사진',
    sortOrder: 4,
    legacyKey: 'choi-il-hyun',
    isPublished: true,
  },
];

export const getVerifiedExperts = () => VERIFIED_EXPERT_PROFILES;
